# This is a sample aws-auth-patch.yml file.
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::490359941494:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1O1FDNKQVAWFV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::490359941494:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-17T11:34:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1654"
  uid: b4de3f61-167b-4645-b234-2ca260a05b3b
